---
- import_playbook: vault.yaml
  tags:
    - vault

- import_playbook: nomad.yaml
  tags:
    - nomad

- import_playbook: cockroach.yaml
  tags:
    - cockroach

- import_playbook: public_gateway.yaml
  tags:
    - public_gateway
