---
# @meta description: >
# Requires all core infrastructure components to be deployed and configured
#
# - Deploy Kong as ingress gateway in Nomad
# - Configure Nginx on public facing Proxy
# @end

- ansible.builtin.import_tasks: ../../common-tasks/nomad_login/nomad_login.yaml
- ansible.builtin.import_tasks: ../../common-tasks/consul_login/consul_login.yaml

- run_once: true
  delegate_to: localhost
  become: false
  environment:
    NOMAD_ADDR: "{{ nomad.url }}"
    NOMAD_TOKEN: "{{ nomad_token }}"
    CONSUL_HTTP_ADDR: "{{ consul.url }}"
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"
  block:
    - name: Ensure working directory
      ansible.builtin.file:
        path: /tmp/services/public_gateway/intentions
        state: directory

    - ansible.builtin.set_fact:
        gateway_services: "{{ services.services | selectattr('use_ingress_gateway', 'true') }}"

    - name: Copy intentions configurations to working directory
      ansible.builtin.template:
        src: consul-intention.json.j2
        dest: /tmp/services/public_gateway/intentions/{{ item.name }}.json
      with_items: "{{ gateway_services }}"

    - name: Create consul intentions
      ansible.builtin.command: >-
        consul config write /tmp/services/public_gateway/intentions/{{ item.name }}.json
      with_items: "{{ gateway_services }}"

    - name: Copy proxy nomad job to working directory
      ansible.builtin.template:
        src: proxy.nomad.j2
        dest: /tmp/services/public_gateway/proxy.nomad

    - name: Deploy proxy to nomad
      ansible.builtin.command: >-
        nomad job run /tmp/services/public_gateway/proxy.nomad

- name: Copy services gateway nginx config template
  ansible.builtin.template:
    src: services_gateway.conf.tpl.j2
    dest: "{{ consul_template.data_dir }}/services_gateway.conf.tpl"
    owner: root
    group: root
    mode: "440"
  notify: consul-template unit Restarted

- name: Copy services gateway consul-template config
  ansible.builtin.template:
    src: services_gateway_conf_ctmpl.hcl.j2
    dest: "{{ consul_template.config_dir }}/services_gateway_conf_ctmpl.hcl"
    owner: root
    group: root
    mode: "440"
  notify: consul-template unit Restarted
