---
# @meta description: >
# Requires [Vault](../../vault/) to be run in order to use consul secret engine
#
# - Generate initial gossip encryption key
# - Install and configure [consul-template](https://github.com/hashicorp/consul-template) in order to update consul agent configuration when gossip key gets rotated
# @end
#
# @todo automation: Periodically rotate gossip encryption key

- ansible.builtin.import_tasks: ../../common-tasks/consul-template/consul-template.yaml

- ansible.builtin.import_tasks: ../../common-tasks/vault_login/vault_login.yaml

- run_once: true
  delegate_to: localhost
  become: false
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_token }}"
  block:
    - name: Ensure working directory
      ansible.builtin.file:
        path: /tmp/consul/gossip
        state: directory

    - name: Ensure vault kv2 is enabled
      ansible.builtin.command: |
        vault secrets enable -version 2 -path kv2 kv
      register: enable_kv2_out
      failed_when: enable_kv2_out.rc != 0 and 'path is already in use' not in enable_kv2_out.stderr

    - name: Generate gossip encryption key
      ansible.builtin.command: consul keygen
      register: gossip_key_out

    - ansible.builtin.set_fact:
        gossip_key: "{{ gossip_key_out.stdout }}"

    - name: Save gossip key to vault
      ansible.builtin.command: |
        vault kv put -mount=kv2 /consul/config/encryption \
          key={{ gossip_key }}

    - name: Copy renew-consul-gossip policy to working directory
      ansible.builtin.copy:
        src: renew-consul-gossip-key.policy.hcl
        dest: /tmp/consul/gossip/renew-consul-gossip-key.policy.hcl

    - name: Create policy
      ansible.builtin.command: |
        vault policy write renew-consul-gossip-key \
          /tmp/consul/gossip/renew-consul-gossip-key.policy.hcl

    - name: Get vault token
      ansible.builtin.command: |
        vault token create -field=token \
          -policy=renew-consul-gossip-key \
          -period=24h
      register: vault_token_out

- name: Ensure jq is installed
  ansible.builtin.apt:
    name: jq
    state: latest
    update_cache: true

- name: Copy Vault token to token directory
  ansible.builtin.copy:
    content: "{{ vault_token_out.stdout }}"
    dest: "{{ consul_template.token_dir }}/vault/.consul_gossip"
    owner: root
    group: root
    mode: "440"
  notify: consul-template unit Restarted

- name: Copy gossip key consul template config
  ansible.builtin.template:
    src: consul_gossip_ctmpl.hcl
    dest: "{{ consul_template.config_dir }}/consul_gossip_ctmpl.hcl"
    owner: root
    group: root
    mode: "440"
  notify: consul-template unit Restarted

- name: Copy consul server token template
  ansible.builtin.copy:
    src: consul-server.token.tpl
    dest: "{{ consul_template.data_dir }}/consul-server.token.tpl"
  notify: consul-template unit Restarted

- name: Copy gossip key template
  ansible.builtin.copy:
    src: gossip.key.tpl
    dest: "{{ consul_template.data_dir }}/gossip.key.tpl"
  notify: consul-template unit Restarted

- name: Ensure gossip directory
  ansible.builtin.file:
    path: "/opt/consul/gossip"
    state: directory
  notify: consul-template unit Restarted

- name: Copy rotate script
  ansible.builtin.template:
    src: rotate.sh
    dest: "/opt/consul/gossip/rotate_key.sh"
    mode: 0774
  notify: consul-template unit Restarted
