---
# @meta description: >
# - Initialize cockroachdb
# - Create global management user
# @end

- ansible.builtin.import_tasks: ../../common-tasks/vault_login/vault_login.yaml

- run_once: true
  delegate_to: localhost
  become: false
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_token }}"
  block:
    - name: Ensure working directory
      ansible.builtin.file:
        path: /tmp/cockroach/init
        state: directory

    - name: Ensure vault kv2 is enabled
      ansible.builtin.command: |
        vault secrets enable -version 2 -path kv2 kv
      register: enable_kv2_out
      failed_when: enable_kv2_out.rc != 0 and 'path is already in use' not in enable_kv2_out.stderr

    - name: Check global_management password exsits in vault
      ansible.builtin.command: |
        vault kv get -mount=kv2 -field=password /cockroach/clients/global_management
      register: global_management_password_out
      ignore_errors: true

    - when: global_management_password_out.rc != 0
      set_fact:
        global_management_password: "{{ 999999999999999 | random | to_uuid }}"

    - name: Save generated password to vault
      ansible.builtin.command: |
        vault kv put -mount=kv2 /cockroach/clients/global_management \
          password={{ global_management_password }}
      when: global_management_password_out.rc != 0

    - name: Get global_management password from vault
      ansible.builtin.command: |
        vault kv get -mount=kv2 -field=password /cockroach/clients/global_management
      register: global_management_password_out

    - ansible.builtin.set_fact:
        global_management_password: "{{ global_management_password_out.stdout }}"

- run_once: true
  delegate_to: "{{ groups.cockroach[0] }}"
  block:
    - name: Initialize cockroach cluster
      ansible.builtin.command: |
        cockroach init \
          --host {{ ansible_eth1.ipv4.address }}:{{ cockroach.ports.listen }} \
          --certs-dir {{ cockroach.certs_dir }}
      register: init_out
      failed_when: init_out.rc != 0 and 'already been initialized' not in init_out.stderr

    - name: Create management user on cockroach
      ansible.builtin.command: |
        cockroach sql \
          --url postgresql://root@{{ localhost_ip }}:{{ cockroach.ports.sql }}/defaultdb?sslrootcert={{ cockroach.certs_dir }}/ca.crt&sslcert={{ cockroach.certs_dir }}/client.root.crt&sslkey={{ cockroach.certs_dir }}/client.root.key&sslmode=verify-full \
          --execute "CREATE USER IF NOT EXISTS global_management WITH PASSWORD '{{ global_management_password }}';" \
          --execute "ALTER USER global_management WITH PASSWORD '{{ global_management_password }}';" \
          --execute "GRANT admin TO global_management;"
