---
# @meta description: >
# Configure Vault admin role
# - Configure Vault admin role
# @end

- environment:
    VAULT_ADDR: "https://{{ vault.ui_host }}"
    VAULT_TOKEN: "{{ secrets.vault.initial_root_token }}"
  block:
    - name: Ensure working directory
      ansible.builtin.file:
        path: /tmp/vault/admin
        state: directory

    - name: Copy admin policy to working directory
      ansible.builtin.copy:
        src: admin.policy.hcl
        dest: /tmp/vault/admin/

    - name: Create admin policy on vault
      ansible.builtin.command: |
        vault policy write admin /tmp/vault/admin/admin.policy.hcl

    - name: Enable userpass auth method
      ansible.builtin.command: vault auth enable userpass
      register: enable_userpass_out
      failed_when: enable_userpass_out.rc != 0 and 'path is already in use' not in enable_userpass_out.stderr

    - ansible.builtin.set_fact:
        admin_password: "{{ 999999999999999 | random | to_uuid }}"

    - name: Create admin user or update
      ansible.builtin.command: |
        vault write auth/userpass/users/admin \
          password={{ admin_password }} \
          policies=admin
      register: create_admin_out

    - name: Manually add vault admin password to secrets file.
      ansible.builtin.pause:
        prompt: |
          secrets:
            vault:
              admin_password: '{{ admin_password }}'
