---
# @meta description: >
# Requires [Vault](../../vault/) to be run in order to use nomad secret engine
#
# - Bootstrap ACL
# - Enable [nomad secret engine](https://developer.hashicorp.com/vault/docs/secrets/nomad) on Vault
# - Create and configure Nomad management role
# @end

- ansible.builtin.import_tasks: ../../common-tasks/vault_login/vault_login.yaml

- name: Ensure Nomad policies directory
  ansible.builtin.file:
    path: "{{ nomad.policy_dir }}/"
    state: directory
    owner: nomad
    group: nomad
    mode: "755"

- name: Copy nomad acl config
  ansible.builtin.copy:
    src: acl.hcl
    dest: "{{ nomad.config_dir }}/acl.hcl"
    owner: nomad
    group: nomad
    mode: "444"
  notify: Nomad Reloaded

- run_once: true
  delegate_to: localhost
  become: false
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_token }}"
    NOMAD_ADDR: "{{ nomad.url }}"
  block:
    - name: Ensure kv secret engine is enabled on vault
      ansible.builtin.command: |
        vault secrets enable -path=kv kv
      register: enable_kv2_out
      failed_when: enable_kv2_out.rc != 0 and 'path is already in use' not in enable_kv2_out.stderr

    - name: Manually initialize ACL on nomad server
      ansible.builtin.pause:
        prompt: Login to one nomad server and run 'nomad acl bootstrap' save SecretID to 'kv/root/nomad/bootstrap_token' 'token=****'

    - name: Get nomad bootstrap token from vault
      ansible.builtin.command: |
        vault read -field=token \
          kv/root/nomad/bootstrap_token
      register: bootstrap_token_out

    - name: Enable nomad secret engine on vault
      ansible.builtin.command: |
        vault secrets enable -path=nomad nomad
      register: enable_nomad_out
      failed_when: enable_nomad_out.rc != 0 and 'already in use' not in enable_nomad_out.stderr

    - name: Configure nomad secret engine
      ansible.builtin.command: |
        vault write nomad/config/access \
          address={{ nomad.url }} \
          token={{ bootstrap_token_out.stdout }}

    - name: Create management role
      ansible.builtin.command: |
        vault write nomad/role/global_management_role \
          type=management \
          global=true
