---
all:
  vars:
    services:
      github_service_deployer_password_key: PROD_SERVICE_DEPLOYER_PASSWORD
      frontend:
        main: main-website
      backend:
        - name: zitadel
          database: zitadel
          database_user: zitadel_admin
          database_roles:
            - CREATEDB
            - CREATEROLE
            - CREATELOGIN
          use_ingress_gateway: false
        - name: zitadel
          database: zitadel
          database_user: zitadel_user
          use_ingress_gateway: false
        - name: commerce
          database: commerce
          database_user: commerce_user
          use_ingress_gateway: true
          grpc_services:
            - "peoplesmarkets.commerce.v1.OfferService"
            - "peoplesmarkets.commerce.v1.ShopService"
            - "peoplesmarkets.commerce.v1.ShopCustomizationService"
            - "peoplesmarkets.commerce.v1.ShopDomainService"
        - name: payment
          database: payment
          database_user: payment_user
          use_ingress_gateway: true
          grpc_services:
            - "peoplesmarkets.payment.v1.StripeService"
        - name: media
          database: media
          database_user: media_user
          use_ingress_gateway: true
          proxy_extra_configurations:
            - "client_max_body_size 64M;"
          grpc_services:
            - "peoplesmarkets.media.v1.MediaService"
        - name: stripe-webhooks
          database: stripe_webhooks
          database_user: stripe_webhooks_user
          use_ingress_gateway: true
          http_services:
            - "stripe-webhooks/"
