---
all:
  vars:
    services:
      github_service_deployer_password_key: DEV_SERVICE_DEPLOYER_PASSWORD
      services:
        - name: zitadel
          database: zitadel
          database_user: zitadel_admin
          database_roles:
            - CREATEDB
            - CREATEROLE
            - CREATELOGIN
          use_ingress_gateway: false
        - name: zitadel
          database: zitadel
          database_user: zitadel_user
          use_ingress_gateway: false
        - name: commerce
          database: commerce
          database_user: commerce_user
          use_ingress_gateway: true
          grpc_services:
            - "peoplesmarkets.commerce.v1.OfferService"
            - "peoplesmarkets.commerce.v1.MarketBoothService"
        - name: payment
          database: payment
          database_user: payment_user
          use_ingress_gateway: true
          grpc_services:
            - "peoplesmarkets.payment.v1.StripeService"
