---
- name: Ensure systemd resolved config dir
  ansible.builtin.file:
    path: "{{ systemd_resolved_config_dir }}"
    state: directory

- name: Copy consul dns config to systemd resolved config dir
  ansible.builtin.copy:
    src: consul.conf
    dest: "{{ systemd_resolved_config_dir }}/consul.conf"
    owner: root
    group: root
    mode: "644"
  notify: Systemd Resolved Restarted

- name: Link systemd-resolved resolv.cont to /etc/resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
    force: true
    mode: "777"
  notify: Systemd Resolved Restarted
