---
# @meta description: >
# Requires [Grafana Cloud](https://grafana.com/products/cloud/)
#
# - Run [Vector](https://github.com/vectordotdev/vector) nomad job
# @end

- ansible.builtin.import_tasks: ../../common-tasks/nomad_login/nomad_login.yaml

- name: Ensure working directory
  ansible.builtin.file:
    path: /tmp/vector/install
    state: directory

- ansible.builtin.set_fact:
    log_shipper_api_key: "{{ secrets.grafana.log_shipper_api_key }}"

- name: Prepare vector job file
  ansible.builtin.template:
    src: vector.nomad.j2
    dest: /tmp/vector/install/vector.nomad

- name: Deploy Vector nomad job
  ansible.builtin.command: |
    nomad job run \
      -address={{ nomad.url }} \
      -token={{ nomad_token }} \
      /tmp/vector/install/vector.nomad
